# Generated by Django 5.2.5 on 2026-08-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('phone', models.CharField(help_text='Com DDD, ex: +55 (11) 99999-9999.', max_length=20, verbose_name='telefone')),
                ('receives_daily_tasks', models.BooleanField(default=True, help_text='Envio automático às 10h com projetos/técnicos/tarefas alocados para hoje.', verbose_name='recebe tarefas do dia (10h)')),
                ('receives_project_updates', models.BooleanField(default=True, help_text='Envio automático às 17h com as tarefas concluídas no dia em cada projeto.', verbose_name='recebe atualização de projetos (17h)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Destinatário do Bot',
                'verbose_name_plural': 'Destinatários do Bot',
                'ordering': ('name',),
            },
        ),
    ]
