# Generated by Django 5.2.5 on 2026-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscriber',
            name='receives_operations_print',
            field=models.BooleanField(default=True, help_text='Envio automático de uma imagem com o painel da Central de Operações (Operação do Dia).', verbose_name='recebe print da Operação do Dia (8h, 10h, 12h, 14h, 16h, 18h)'),
        ),
    ]
