"""Textos fixos dos e-mails do sistema em português, inglês e espanhol.

Conteúdo digitado por usuários (atividades, observações, nomes) não é traduzido.
"""

TEXTS = {
    "pt": {
        "not_informed": "Não informado",
        "not_informed_pl": "Não informados",
        "yes": "Sim",
        "no": "Não",
        "project_subject": "Atualização de Projeto",
        "project_title": "Atualização de Projeto",
        "project_intro": "Segue a atualização do projeto. O relatório completo está anexo em PDF.",
        "completion": "Conclusão do projeto",
        "project": "Projeto",
        "code": "Código",
        "site": "Site",
        "po": "PO",
        "po_missing": "Não informada",
        "responsible": "Responsável {client}",
        "responsible_company": "Responsável Consultimer",
        "client_fallback": "Cliente",
        "date": "Data",
        "team": "Equipe",
        "certification": "Certificação finalizada",
        "finished": "Projeto finalizado",
        "occ_status": {"open": "Aberta", "in_progress": "Em andamento", "resolved": "Resolvida", "canceled": "Cancelada"},
        "observations": "Observações",
        "no_observations": "Nenhuma observação.",
        "attachment_note": "Relatório completo em anexo (PDF).",
        "daily_subject": "Alocação Diária",
        "daily_title": "Alocação Diária",
        "daily_intro": "Segue a alocação das equipes para {date}. O relatório completo está anexo em PDF.",
        "sent_by": "Enviado por",
        "reset_subject": "Redefinição de senha",
    },
    "en": {
        "not_informed": "Not provided",
        "not_informed_pl": "Not provided",
        "yes": "Yes",
        "no": "No",
        "project_subject": "Project Update",
        "project_title": "Project Update",
        "project_intro": "Please find the project update below. The full report is attached as a PDF.",
        "completion": "Project completion",
        "project": "Project",
        "code": "Code",
        "site": "Site",
        "po": "PO",
        "po_missing": "Not provided",
        "responsible": "{client} contact",
        "responsible_company": "Consultimer contact",
        "client_fallback": "Client",
        "date": "Date",
        "team": "Team",
        "certification": "Certification completed",
        "finished": "Project completed",
        "occ_status": {"open": "Open", "in_progress": "In progress", "resolved": "Resolved", "canceled": "Canceled"},
        "observations": "Notes",
        "no_observations": "No notes.",
        "attachment_note": "Full report attached (PDF).",
        "daily_subject": "Daily Allocation",
        "daily_title": "Daily Allocation",
        "daily_intro": "Please find the team allocation for {date}. The full report is attached as a PDF.",
        "sent_by": "Sent by",
        "reset_subject": "Password reset",
    },
    "es": {
        "not_informed": "No informado",
        "not_informed_pl": "No informados",
        "yes": "Sí",
        "no": "No",
        "project_subject": "Actualización de Proyecto",
        "project_title": "Actualización de Proyecto",
        "project_intro": "A continuación la actualización del proyecto. El informe completo está adjunto en PDF.",
        "completion": "Avance del proyecto",
        "project": "Proyecto",
        "code": "Código",
        "site": "Sitio",
        "po": "PO",
        "po_missing": "No informada",
        "responsible": "Responsable {client}",
        "responsible_company": "Responsable Consultimer",
        "client_fallback": "Cliente",
        "date": "Fecha",
        "team": "Equipo",
        "certification": "Certificación finalizada",
        "finished": "Proyecto finalizado",
        "occ_status": {"open": "Abierta", "in_progress": "En curso", "resolved": "Resuelta", "canceled": "Cancelada"},
        "observations": "Observaciones",
        "no_observations": "Ninguna observación.",
        "attachment_note": "Informe completo adjunto (PDF).",
        "daily_subject": "Asignación Diaria",
        "daily_title": "Asignación Diaria",
        "daily_intro": "A continuación la asignación de los equipos para {date}. El informe completo está adjunto en PDF.",
        "sent_by": "Enviado por",
        "reset_subject": "Restablecimiento de contraseña",
    },
}

DATE_FORMAT = {"pt": "%d/%m/%Y", "en": "%m/%d/%Y", "es": "%d/%m/%Y"}


def tr(lang, key, **kwargs):
    text = TEXTS[lang][key]
    return text.format(**kwargs) if kwargs else text


def fmt_date(lang, value):
    return value.strftime(DATE_FORMAT[lang])
