# Generated by Django 5.2.5 on 2026-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciandailypresence',
            name='status',
            field=models.CharField(choices=[('not_started', 'Não chegou'), ('available', 'Disponível'), ('lunch', 'Almoço'), ('personal', 'Particular'), ('off_duty', 'Fim de Expediente')], default='not_started', max_length=20, verbose_name='status'),
        ),
    ]
