# Generated by Django 5.2.5 on 2026-08-29 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notification'),
        ('dispatch', '0004_alter_techniciandailypresence_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('status', models.CharField(choices=[('not_started', 'Não chegou'), ('available', 'Disponível'), ('lunch', 'Horário de Almoço'), ('personal', 'Particular'), ('site_blocked', 'Sem Acesso ao Site'), ('awaiting_release', 'Aguardando Liberações'), ('off_duty', 'Fim de Expediente')], max_length=20, verbose_name='status')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alterado em')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='core.collaborator', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'Troca de Status do Técnico',
                'verbose_name_plural': 'Trocas de Status dos Técnicos',
                'ordering': ('changed_at',),
            },
        ),
    ]
