# Generated by Django 5.2.5 on 2026-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_technicianstatusevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciandailypresence',
            name='status',
            field=models.CharField(choices=[('not_started', 'Não chegou'), ('available', 'Disponível'), ('in_progress', 'Em Execução'), ('lunch', 'Horário de Almoço'), ('personal', 'Particular'), ('site_blocked', 'Sem Acesso ao Site'), ('awaiting_release', 'Aguardando Liberações'), ('off_duty', 'Fim de Expediente')], default='not_started', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='technicianstatusevent',
            name='status',
            field=models.CharField(choices=[('not_started', 'Não chegou'), ('available', 'Disponível'), ('in_progress', 'Em Execução'), ('lunch', 'Horário de Almoço'), ('personal', 'Particular'), ('site_blocked', 'Sem Acesso ao Site'), ('awaiting_release', 'Aguardando Liberações'), ('off_duty', 'Fim de Expediente')], max_length=20, verbose_name='status'),
        ),
    ]
