# Generated by Django 5.2.5 on 2026-08-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notification'),
        ('dispatch', '0006_alter_techniciandailypresence_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('collaborator_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_a', to='core.collaborator', verbose_name='técnico A')),
                ('collaborator_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_b', to='core.collaborator', verbose_name='técnico B')),
            ],
            options={
                'verbose_name': 'Dupla de Técnicos',
                'verbose_name_plural': 'Duplas de Técnicos',
                'ordering': ('collaborator_a__person__name',),
            },
        ),
    ]
