# Generated by Django 5.2.5 on 2026-08-31 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notification'),
        ('dispatch', '0008_alter_techniciandailypresence_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date_from', models.DateField(verbose_name='de')),
                ('date_to', models.DateField(verbose_name='até')),
                ('reason', models.CharField(blank=True, help_text='Ex: Férias, Atestado médico, Folga.', max_length=150, verbose_name='motivo')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.collaborator', verbose_name='técnico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Ausência de Técnico',
                'verbose_name_plural': 'Ausências de Técnico',
                'ordering': ('-date_from',),
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='absence_date_to_after_from')],
            },
        ),
    ]
