# Generated by Django 5.2.5 on 2026-08-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
            ],
            options={
                'verbose_name': 'Minha Tarefa',
                'verbose_name_plural': 'Minhas Tarefas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.projecttask',),
        ),
    ]
