# Generated by Django 5.2.5 on 2026-08-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_alter_projecttype_options_alter_task_project_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ano')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='último número')),
            ],
            options={
                'verbose_name': 'Sequência de Projetos',
                'verbose_name_plural': 'Sequências de Projetos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome do projeto')),
                ('po', models.CharField(blank=True, max_length=100, verbose_name='PO')),
                ('responsible_client', models.CharField(blank=True, max_length=150, verbose_name='Responsável Cliente')),
                ('status', models.CharField(choices=[('planning', 'Planejamento'), ('not_started', 'Não Iniciado'), ('in_progress', 'Em Andamento'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='planning', max_length=20, verbose_name='status')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='início previsto')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='término previsto')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='início real')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='término real')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.category', verbose_name='categoria')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.client', verbose_name='cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.company', verbose_name='empresa')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name__icontains', 'Supervisor'), ('job_title__name__icontains', 'Coordenador'), ('job_title__name__icontains', 'Gerente'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to='core.collaborator', verbose_name='gestor')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.projecttype', verbose_name='Tipo de Projeto')),
                ('responsible_cstr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.responsible', verbose_name='Responsável CSTR')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciada'), ('in_progress', 'Em Andamento'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='not_started', max_length=20, verbose_name='status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='início previsto')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='término previsto')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='início real')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='término real')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='horas previstas')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='horas realizadas')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_tasks', to='core.collaborator', verbose_name='colaborador responsável')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project', verbose_name='projeto')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tasks', to='core.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa do Projeto',
                'verbose_name_plural': 'Tarefas do Projeto',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('project', 'task'), name='unique_task_per_project')],
            },
        ),
    ]
