# Generated by Django 5.2.5 on 2026-08-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clientresponsible'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.clientresponsible', verbose_name='Responsável Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_cstr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('company__legal_name__icontains', 'CONSULTIMER'), ('company__trade_name__icontains', 'CONSULTIMER'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.responsible', verbose_name='Responsável CSTR'),
        ),
    ]
