# Generated by Django 5.2.5 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttask",
            name="planned_start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Início"),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="planned_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Término"),
        ),
    ]
