# Generated by Django 5.2.5 on 2026-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projecttask_paused_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_count',
            field=models.PositiveIntegerField(default=0, verbose_name='quantidade de links'),
        ),
    ]
