# Generated by Django 5.2.5 on 2026-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_link_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='quantidade de links'),
        ),
    ]
