# Generated by Django 5.2.5 on 2026-08-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_link_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_rack_positions',
            field=models.BooleanField(default=False, help_text='Ative para controlar Rack Position (DH, Links, UTP por posição) neste projeto.', verbose_name='Rack Position'),
        ),
        migrations.CreateModel(
            name='RackPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('position', models.CharField(max_length=50, verbose_name='Rack Position')),
                ('dh', models.CharField(blank=True, max_length=50, verbose_name='DH')),
                ('links', models.PositiveIntegerField(blank=True, default=0, verbose_name='Links')),
                ('utp', models.PositiveIntegerField(blank=True, default=0, verbose_name='UTP')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_positions', to='projects.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'Rack Position',
                'verbose_name_plural': 'Rack Positions',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='rack_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='projects.rackposition', verbose_name='Rack Position'),
        ),
        migrations.AddConstraint(
            model_name='rackposition',
            constraint=models.UniqueConstraint(fields=('project', 'position'), name='unique_rack_position_per_project'),
        ),
    ]
