# Generated by Django 5.2.5 on 2026-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_has_rack_positions_rackposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='has_rack_positions',
            field=models.BooleanField(blank=True, default=False, help_text='Ative para controlar Rack Position (DH, Links, UTP por posição) neste projeto.', verbose_name='Rack Position'),
        ),
    ]
