# Generated by Django 5.2.5 on 2026-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_has_rack_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='rack_position',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='rack_positions',
            field=models.ManyToManyField(blank=True, related_name='project_tasks', to='projects.rackposition', verbose_name='Rack Positions'),
        ),
    ]
