# Generated by Django 5.2.5 on 2026-08-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projecttask_rack_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
