# Generated by Django 5.2.5 on 2026-08-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_dashboardproxy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projecttask',
            name='unique_task_per_project',
        ),
    ]
