# Generated by Django 5.2.5 on 2026-08-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_person_finalize'),
        ('projects', '0015_remove_projecttask_unique_task_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='responsible_cstr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('person__company__legal_name__icontains', 'CONSULTIMER'), ('person__company__trade_name__icontains', 'CONSULTIMER'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.responsible', verbose_name='Responsável CSTR'),
        ),
    ]
