# Generated by Django 5.2.5 on 2026-08-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_clientresponsible'),
        ('projects', '0018_responsible_client_swap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='responsible_cstr',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('kind', 'cstr'), models.Q(('person__company__legal_name__icontains', 'CONSULTIMER'), ('person__company__trade_name__icontains', 'CONSULTIMER'), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cstr_projects', to='core.responsible', verbose_name='Responsável CSTR'),
        ),
    ]
