# Generated by Django 5.2.5 on 2026-08-16 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_collaborator_options'),
        ('projects', '0019_alter_project_responsible_cstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='criticidade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvida'), ('canceled', 'Cancelada')], default='open', max_length=20, verbose_name='status')),
                ('occurred_at', models.DateField(default=django.utils.timezone.now, verbose_name='data da ocorrência')),
                ('resolved_at', models.DateField(blank=True, null=True, verbose_name='data de resolução')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='projects.project', verbose_name='projeto')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='core.collaborator', verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'Ocorrência do Projeto',
                'verbose_name_plural': 'Ocorrências do Projeto',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
    ]
