# Generated by Django 5.2.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_projectoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(upload_to=projects.models.project_attachment_upload_to, verbose_name='arquivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project', verbose_name='projeto')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_attachments', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'Anexo do Projeto',
                'verbose_name_plural': 'Anexos do Projeto',
                'ordering': ('-created_at',),
            },
        ),
    ]
