# Generated by Django 5.2.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='custom_name',
            field=models.CharField(
                blank=True,
                help_text="Usado só quando a tarefa não vem do catálogo (campo 'Tarefa' em branco).",
                max_length=200,
                verbose_name='nome da tarefa avulsa',
            ),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='project_tasks',
                to='core.task',
                verbose_name='tarefa',
            ),
        ),
    ]
