# Generated by Django 5.2.5 on 2026-08-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notification'),
        ('projects', '0025_projecttask_collaborators_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttaskassignment',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='core.collaborator'),
        ),
    ]
