# Generated by Django 5.2.5 on 2026-08-30 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_activitytype_projectitemtype'),
        ('projects', '0026_alter_projecttaskassignment_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_tasks', to='core.activitytype', verbose_name='tipo de atividade'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='complexity',
            field=models.CharField(blank=True, choices=[('simple', 'Simples'), ('medium', 'Média'), ('complex', 'Complexa')], max_length=20, verbose_name='complexidade'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='instruções'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, verbose_name='prioridade'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='quantity_completed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade concluída'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='quantity_planned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade planejada'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text="Posição da atividade dentro da cadeia do item (ex: Lançamento=1, Organização=2...) — não confundir com 'ordem' (exibição geral) nem com a fila de despacho do técnico.", verbose_name='sequência'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='unit',
            field=models.CharField(blank=True, help_text='Ex: m, un, porta, ponta, link, caixa.', max_length=20, verbose_name='unidade'),
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_code', models.CharField(blank=True, max_length=50, verbose_name='código interno')),
                ('technology', models.CharField(blank=True, max_length=100, verbose_name='tecnologia')),
                ('fiber_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de fibras')),
                ('connector_type_a', models.CharField(blank=True, max_length=50, verbose_name='tipo de conector A')),
                ('connector_type_b', models.CharField(blank=True, max_length=50, verbose_name='tipo de conector B')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='part number')),
                ('length_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='metragem')),
                ('origin', models.CharField(blank=True, max_length=150, verbose_name='origem')),
                ('destination', models.CharField(blank=True, max_length=150, verbose_name='destino')),
                ('route', models.CharField(blank=True, max_length=255, verbose_name='rota')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='prioridade')),
                ('complexity', models.CharField(choices=[('simple', 'Simples'), ('medium', 'Média'), ('complex', 'Complexa')], default='medium', max_length=20, verbose_name='complexidade')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='not_started', max_length=20, verbose_name='status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_items', to='core.projectitemtype', verbose_name='tipo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'Item do Projeto',
                'verbose_name_plural': 'Itens do Projeto',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_tasks', to='projects.projectitem', verbose_name='item do projeto'),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='projects.projecttask', verbose_name='depende de')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.projecttask', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'Dependência de Tarefa',
                'verbose_name_plural': 'Dependências de Tarefa',
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DISPATCHED', 'Despachada'), ('STARTED', 'Iniciada'), ('PAUSED', 'Pausada'), ('RESUMED', 'Retomada'), ('COMPLETED', 'Concluída'), ('REOPENED', 'Reaberta'), ('CANCELLED', 'Cancelada')], max_length=20, verbose_name='evento')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('quantity_delta', models.DecimalField(blank=True, decimal_places=2, help_text='Incremento concluído NESTE evento — não o total acumulado.', max_digits=10, null=True, verbose_name='quantidade incremental')),
                ('productive_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='segundos produtivos')),
                ('unproductive_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='segundos improdutivos')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_execution_events', to='core.collaborator', verbose_name='técnico')),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_events', to='projects.projecttask', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'Evento de Execução',
                'verbose_name_plural': 'Eventos de Execução',
                'ordering': ('occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_blocks', to='projects.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'Bloco de Trabalho',
                'verbose_name_plural': 'Blocos de Trabalho',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='projectitem',
            name='work_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='projects.workblock', verbose_name='bloco de trabalho'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='work_block',
            field=models.ForeignKey(blank=True, help_text='Preenchido automaticamente a partir do bloco do item do projeto (ver save()).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='projects.workblock', verbose_name='bloco de trabalho'),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.UniqueConstraint(condition=models.Q(('project_item__isnull', False), ('activity_type__isnull', False)), fields=('project_item', 'activity_type'), name='unique_activity_per_item'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='dependency_not_self'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionevent',
            index=models.Index(fields=['project_task', 'occurred_at'], name='projects_ta_project_405a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionevent',
            index=models.Index(fields=['collaborator', 'occurred_at'], name='projects_ta_collabo_8cd671_idx'),
        ),
        migrations.AddConstraint(
            model_name='workblock',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('project', 'name'), name='unique_nonempty_workblock_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project', 'work_block'], name='projects_pr_project_8d67d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectitem',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code', ''), _negated=True), fields=('project', 'internal_code'), name='unique_nonempty_item_code_per_project'),
        ),
    ]
