# Generated by Django 5.2.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_import', '0001_initial'),
        ('projects', '0027_projecttask_activity_type_projecttask_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workblock',
            name='scope_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_blocks_created', to='scope_import.scopeimport', verbose_name='importação de escopo'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='scope_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to='scope_import.scopeimport', verbose_name='importação de escopo'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='scope_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='scope_import.scopeimport', verbose_name='importação de escopo'),
        ),
    ]
