# Generated by Django 5.2.5 on 2026-09-13 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('medium', models.CharField(choices=[('FIBER', 'Fibra'), ('COPPER', 'Cobre')], default='FIBER', max_length=10, verbose_name='meio')),
                ('fiber_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='nº de fibras')),
                ('connector_a', models.CharField(blank=True, max_length=50, verbose_name='conector A')),
                ('connector_b', models.CharField(blank=True, max_length=50, verbose_name='conector B')),
                ('cable_category', models.CharField(blank=True, max_length=50, verbose_name='categoria do cabo')),
                ('preterminated', models.BooleanField(default=False, verbose_name='pré-terminado')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'Família de Cabo',
                'verbose_name_plural': 'Famílias de Cabo',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CableAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('alias_text', models.CharField(max_length=150, verbose_name='texto do alias')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('cable_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='master_data.cablefamily', verbose_name='família de cabo')),
            ],
            options={
                'verbose_name': 'Alias de Cabo',
                'verbose_name_plural': 'Aliases de Cabo',
                'ordering': ('alias_text',),
                'constraints': [models.UniqueConstraint(fields=('cable_family', 'alias_text'), name='unique_alias_per_family')],
            },
        ),
    ]
