# Generated by Django 5.2.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0027_projecttask_activity_type_projecttask_complexity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('raw_text', models.TextField(verbose_name='escopo colado')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('processing', 'Processando'), ('ready', 'Pronto para revisão'), ('failed', 'Falhou'), ('confirmed', 'Confirmado'), ('discarded', 'Descartado')], default='draft', max_length=20, verbose_name='status')),
                ('ai_provider', models.CharField(blank=True, max_length=50, verbose_name='provedor de IA')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='modelo de IA')),
                ('ai_raw_response', models.JSONField(blank=True, null=True, verbose_name='resposta bruta da IA')),
                ('reviewed_payload', models.JSONField(blank=True, null=True, verbose_name='versão revisada (usada na confirmação)')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_imports', to='projects.project', verbose_name='projeto')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_imports_requested', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_imports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
            ],
            options={
                'verbose_name': 'Importação de Escopo',
                'verbose_name_plural': 'Importações de Escopo',
                'ordering': ('-created_at',),
            },
        ),
    ]
