import type { ViewId } from "./IndicatorsTrends";

type Segment = "operation" | "production" | "compare" | "quality";

export type Text = {
  eyebrow: string;
  title: string;
  subtitle: string;
  site: string;
  cliente: string;
  regional: string;
  todosSites: string;
  todosClientes: string;
  todasRegionais: string;
  agrupar: string;
  day: string;
  week: string;
  month: string;
  auto: string;
  preset: (d: number) => string;
  dias: string;
  series: Record<string, string>;
  segments: Record<Segment, string>;
  views: Record<ViewId, string>;
  notes: Record<ViewId, string>;
  dimensions: Record<"site" | "client" | "region", string>;
  bands: Record<"low" | "warn" | "ok" | "suspect", string>;
  others: string;
  currentPeriod: string;
  previousPeriod: string;
  compararPor: string;
  medida: string;
  atividade: string;
  execucoes: string;
  semProdutividade: string;
  technician: string;
  total: string;
  periodo: string;
  verTabela: string;
  verGrafico: string;
  carregando: string;
  erro: string;
  tentarNovamente: string;
  vazio: string;
  ocultar: string;
};

export const TEXT: Record<"pt-BR" | "en-US" | "es-ES", Text> = {
  "pt-BR": {
    eyebrow: "Indicadores",
    title: "Tendências",
    subtitle: "Evolução da operação, da produção e da qualidade do apontamento",
    site: "Site",
    cliente: "Cliente",
    regional: "Regional",
    todosSites: "Todos os sites",
    todosClientes: "Todos os clientes",
    todasRegionais: "Todas as regionais",
    agrupar: "Agrupar por",
    day: "Dia",
    week: "Semana",
    month: "Mês",
    auto: "Automático",
    preset: (d) => (d === 365 ? "1 ano" : `${d} dias`),
    dias: "dias",
    series: {
      hours_execution: "Horas em execução",
      hours_unproductive: "Horas improdutivas",
      tasks_executed: "Tarefas executadas",
      utilization_pct: "Utilização da jornada",
      hours_external_block: "Bloqueio externo",
      hours_internal_idle: "Ocioso interno",
      man_hours: "Homem-hora (HH)",
      tasks_created: "Tarefas criadas",
      tasks_completed: "Tarefas concluídas",
      tasks_planned: "Tarefas planejadas",
      backlog: "Fila de tarefas abertas",
      hours_estimated: "Horas previstas",
      hours_real: "Horas reais",
      no_hours: "Sem horas apontadas",
      batch: "Lançadas em lote",
      incomplete_days: "Dias de presença incompletos",
    },
    segments: { operation: "Operação", production: "Produção", compare: "Comparativos", quality: "Qualidade do apontamento" },
    views: {
      overview: "Visão geral",
      utilization: "Utilização da jornada",
      unproductive: "Improdutivo por causa",
      manhours: "Homem-hora (HH)",
      heatmap: "Mapa de calor de técnicos",
      flow: "Criadas × concluídas",
      backlog: "Fila de tarefas",
      planning: "Planejadas × concluídas",
      estimate: "Horas previstas × reais",
      productivity: "Produtividade por atividade",
      by: "Por site, cliente ou regional",
      previous: "Período anterior",
      quality: "Apontamento suspeito",
      incomplete: "Presença incompleta",
    },
    notes: {
      overview: "Horas: tempo em execução (e apoio) e tempo improdutivo (disponível sem tarefa + bloqueio externo) dos técnicos lotados nos sites filtrados. Tarefas: conclusões no período. Mesmas regras de Relatórios e Indicadores. Todas as séries usam o mesmo eixo.",
      utilization: "Horas em execução ÷ jornada (8 h por dia com check-in). A linha tracejada marca 70%, o início da faixa normal; acima de 100% o dado é suspeito.",
      unproductive: "Bloqueio externo: site bloqueado ou aguardando liberação (depende do cliente). Ocioso interno: disponível sem tarefa (depende da programação).",
      manhours: "HH soma as horas reais de cada técnico: numa tarefa em dupla conta duas vezes, por isso fica acima das horas em execução.",
      heatmap: "Utilização de cada técnico por período, em ordem decrescente. Mostra até 80 técnicos com jornada no período. Cores: vermelho < 50%, âmbar 50–69%, verde 70–100%, roxo > 100% (dado suspeito).",
      flow: "Tarefas criadas (inclui importação de escopo) contra tarefas concluídas no período. Tarefas ignoradas nos relatórios e canceladas não contam.",
      backlog: "Tarefas abertas ao fim de cada período: criadas até ali menos concluídas até ali (canceladas não contam).",
      planning: "Tarefas com término planejado no período contra tarefas efetivamente concluídas no mesmo período.",
      estimate: "Só tarefas concluídas no período que têm horas previstas e horas reais. Horas reais são as da tarefa, não o HH.",
      productivity: "Quantidade creditada ÷ horas apontadas, por atividade, só de execuções válidas (sem valor absurdo ou parcial). Escolha a atividade; cada uma tem a sua unidade.",
      by: "Cada técnico entra no site, cliente ou regional do seu site principal (o primeiro, em ordem alfabética). Até 7 grupos; o restante vai em Outros.",
      previous: "Período anterior de mesmo tamanho, imediatamente antes do atual, alinhado por posição. Linha tracejada = anterior.",
      quality: "Conclusões de técnico sem horas apontadas ou lançadas em lote (menos de 1 minuto). Valores altos tornam o HH menos confiável.",
      incomplete: "Dias em que o último status do técnico não foi Fim de Expediente nem Em Execução (o dia é cortado em check-in + 9 h).",
    },
    dimensions: { site: "Site", client: "Cliente", region: "Regional" },
    bands: { low: "< 50%", warn: "50–69%", ok: "70–100%", suspect: "> 100% (suspeito)" },
    others: "Outros",
    currentPeriod: "Período atual",
    previousPeriod: "Período anterior",
    compararPor: "Comparar por",
    medida: "Medida",
    atividade: "Atividade",
    execucoes: "execuções",
    semProdutividade: "Nenhuma atividade com execuções válidas no período e filtros escolhidos.",
    technician: "Técnico",
    total: "Total",
    periodo: "Período",
    verTabela: "Ver tabela",
    verGrafico: "Ver gráfico",
    carregando: "Carregando…",
    erro: "Não foi possível carregar os indicadores.",
    tentarNovamente: "Tentar novamente",
    vazio: "Sem dados para os filtros e o período escolhidos.",
    ocultar: "Clique para ocultar/mostrar a série",
  },
  "en-US": {
    eyebrow: "Indicators",
    title: "Trends",
    subtitle: "Evolution of operations, production and timekeeping quality",
    site: "Site",
    cliente: "Client",
    regional: "Region",
    todosSites: "All sites",
    todosClientes: "All clients",
    todasRegionais: "All regions",
    agrupar: "Group by",
    day: "Day",
    week: "Week",
    month: "Month",
    auto: "Automatic",
    preset: (d) => (d === 365 ? "1 year" : `${d} days`),
    dias: "days",
    series: {
      hours_execution: "Execution hours",
      hours_unproductive: "Unproductive hours",
      tasks_executed: "Tasks executed",
      utilization_pct: "Workday utilization",
      hours_external_block: "External block",
      hours_internal_idle: "Internal idle",
      man_hours: "Man-hours (MH)",
      tasks_created: "Tasks created",
      tasks_completed: "Tasks completed",
      tasks_planned: "Tasks planned",
      backlog: "Open task queue",
      hours_estimated: "Estimated hours",
      hours_real: "Actual hours",
      no_hours: "No hours logged",
      batch: "Batch-entered",
      incomplete_days: "Incomplete presence days",
    },
    segments: { operation: "Operations", production: "Production", compare: "Comparisons", quality: "Timekeeping quality" },
    views: {
      overview: "Overview",
      utilization: "Workday utilization",
      unproductive: "Unproductive by cause",
      manhours: "Man-hours (MH)",
      heatmap: "Technician heatmap",
      flow: "Created × completed",
      backlog: "Task queue",
      planning: "Planned × completed",
      estimate: "Estimated × actual hours",
      productivity: "Productivity by activity",
      by: "By site, client or region",
      previous: "Previous period",
      quality: "Suspect timekeeping",
      incomplete: "Incomplete presence",
    },
    notes: {
      overview: "Hours: time in execution (and support) and unproductive time (available without a task + external block) of technicians assigned to the filtered sites. Tasks: completions in the period. Same rules as Reports & Indicators. All series share the same axis.",
      utilization: "Execution hours ÷ workday (8 h per checked-in day). The dashed line marks 70%, the start of the normal band; above 100% the data is suspect.",
      unproductive: "External block: site blocked or awaiting release (depends on the client). Internal idle: available without a task (depends on scheduling).",
      manhours: "MH adds each technician's real hours: a two-person task counts twice, so it sits above execution hours.",
      heatmap: "Each technician's utilization per period, highest first. Shows up to 80 technicians with a workday in the period. Colors: red < 50%, amber 50–69%, green 70–100%, purple > 100% (suspect).",
      flow: "Tasks created (including scope imports) against tasks completed in the period. Tasks ignored in reports and canceled tasks do not count.",
      backlog: "Open tasks at the end of each period: created so far minus completed so far (canceled do not count).",
      planning: "Tasks with a planned end in the period against tasks actually completed in the same period.",
      estimate: "Only tasks completed in the period that have both estimated and actual hours. Actual hours are the task's, not MH.",
      productivity: "Credited quantity ÷ logged hours per activity, valid executions only (no absurd or partial values). Pick the activity; each has its own unit.",
      by: "Each technician belongs to the site, client or region of their main site (the first alphabetically). Up to 7 groups; the rest go to Others.",
      previous: "Previous period of the same length, right before the current one, aligned by position. Dashed line = previous.",
      quality: "Technician completions with no logged hours or entered in batch (under 1 minute). High values make MH less reliable.",
      incomplete: "Days when the technician's last status was neither End of Shift nor In Execution (the day is cut at check-in + 9 h).",
    },
    dimensions: { site: "Site", client: "Client", region: "Region" },
    bands: { low: "< 50%", warn: "50–69%", ok: "70–100%", suspect: "> 100% (suspect)" },
    others: "Others",
    currentPeriod: "Current period",
    previousPeriod: "Previous period",
    compararPor: "Compare by",
    medida: "Measure",
    atividade: "Activity",
    execucoes: "executions",
    semProdutividade: "No activity with valid executions in the chosen period and filters.",
    technician: "Technician",
    total: "Total",
    periodo: "Period",
    verTabela: "View table",
    verGrafico: "View chart",
    carregando: "Loading…",
    erro: "Could not load the indicators.",
    tentarNovamente: "Try again",
    vazio: "No data for the chosen filters and period.",
    ocultar: "Click to hide/show the series",
  },
  "es-ES": {
    eyebrow: "Indicadores",
    title: "Tendencias",
    subtitle: "Evolución de la operación, la producción y la calidad del registro",
    site: "Sitio",
    cliente: "Cliente",
    regional: "Regional",
    todosSites: "Todos los sitios",
    todosClientes: "Todos los clientes",
    todasRegionais: "Todas las regionales",
    agrupar: "Agrupar por",
    day: "Día",
    week: "Semana",
    month: "Mes",
    auto: "Automático",
    preset: (d) => (d === 365 ? "1 año" : `${d} días`),
    dias: "días",
    series: {
      hours_execution: "Horas en ejecución",
      hours_unproductive: "Horas improductivas",
      tasks_executed: "Tareas ejecutadas",
      utilization_pct: "Utilización de la jornada",
      hours_external_block: "Bloqueo externo",
      hours_internal_idle: "Ocioso interno",
      man_hours: "Hombre-hora (HH)",
      tasks_created: "Tareas creadas",
      tasks_completed: "Tareas concluidas",
      tasks_planned: "Tareas planificadas",
      backlog: "Cola de tareas abiertas",
      hours_estimated: "Horas previstas",
      hours_real: "Horas reales",
      no_hours: "Sin horas registradas",
      batch: "Cargadas en lote",
      incomplete_days: "Días de presencia incompletos",
    },
    segments: { operation: "Operación", production: "Producción", compare: "Comparativos", quality: "Calidad del registro" },
    views: {
      overview: "Visión general",
      utilization: "Utilización de la jornada",
      unproductive: "Improductivo por causa",
      manhours: "Hombre-hora (HH)",
      heatmap: "Mapa de calor de técnicos",
      flow: "Creadas × concluidas",
      backlog: "Cola de tareas",
      planning: "Planificadas × concluidas",
      estimate: "Horas previstas × reales",
      productivity: "Productividad por actividad",
      by: "Por sitio, cliente o regional",
      previous: "Período anterior",
      quality: "Registro sospechoso",
      incomplete: "Presencia incompleta",
    },
    notes: {
      overview: "Horas: tiempo en ejecución (y apoyo) y tiempo improductivo (disponible sin tarea + bloqueo externo) de los técnicos asignados a los sitios filtrados. Tareas: conclusiones en el período. Mismas reglas de Reportes e Indicadores. Todas las series usan el mismo eje.",
      utilization: "Horas en ejecución ÷ jornada (8 h por día con check-in). La línea punteada marca 70%, el inicio de la franja normal; sobre 100% el dato es sospechoso.",
      unproductive: "Bloqueo externo: sitio bloqueado o esperando liberación (depende del cliente). Ocioso interno: disponible sin tarea (depende de la programación).",
      manhours: "HH suma las horas reales de cada técnico: una tarea en pareja cuenta dos veces, por eso queda sobre las horas en ejecución.",
      heatmap: "Utilización de cada técnico por período, de mayor a menor. Muestra hasta 80 técnicos con jornada en el período. Colores: rojo < 50%, ámbar 50–69%, verde 70–100%, morado > 100% (sospechoso).",
      flow: "Tareas creadas (incluye importación de alcance) contra tareas concluidas en el período. Las ignoradas en reportes y las canceladas no cuentan.",
      backlog: "Tareas abiertas al final de cada período: creadas hasta ahí menos concluidas hasta ahí (las canceladas no cuentan).",
      planning: "Tareas con fin planificado en el período contra tareas efectivamente concluidas en el mismo período.",
      estimate: "Solo tareas concluidas en el período con horas previstas y reales. Las horas reales son las de la tarea, no el HH.",
      productivity: "Cantidad acreditada ÷ horas registradas por actividad, solo ejecuciones válidas (sin valores absurdos ni parciales). Elige la actividad; cada una tiene su unidad.",
      by: "Cada técnico pertenece al sitio, cliente o regional de su sitio principal (el primero en orden alfabético). Hasta 7 grupos; el resto va en Otros.",
      previous: "Período anterior del mismo tamaño, justo antes del actual, alineado por posición. Línea punteada = anterior.",
      quality: "Conclusiones de técnico sin horas registradas o cargadas en lote (menos de 1 minuto). Valores altos hacen el HH menos confiable.",
      incomplete: "Días en que el último estado del técnico no fue Fin de Jornada ni En Ejecución (el día se corta en check-in + 9 h).",
    },
    dimensions: { site: "Sitio", client: "Cliente", region: "Regional" },
    bands: { low: "< 50%", warn: "50–69%", ok: "70–100%", suspect: "> 100% (sospechoso)" },
    others: "Otros",
    currentPeriod: "Período actual",
    previousPeriod: "Período anterior",
    compararPor: "Comparar por",
    medida: "Medida",
    atividade: "Actividad",
    execucoes: "ejecuciones",
    semProdutividade: "Ninguna actividad con ejecuciones válidas en el período y filtros elegidos.",
    technician: "Técnico",
    total: "Total",
    periodo: "Período",
    verTabela: "Ver tabla",
    verGrafico: "Ver gráfico",
    carregando: "Cargando…",
    erro: "No se pudieron cargar los indicadores.",
    tentarNovamente: "Reintentar",
    vazio: "Sin datos para los filtros y el período elegidos.",
    ocultar: "Clic para ocultar/mostrar la serie",
  },
};
