# Generated by Django 5.2.5 on 2026-08-15 04:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status'),
        ('updates', '0006_limit_daily_update_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data')),
                ('summary', models.TextField(help_text='Texto que será enviado ao cliente descrevendo o andamento do dia.', verbose_name='resumo do progresso')),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='enviado em')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_daily_updates', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_daily_updates', to='projects.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'Atualização Diária de Projeto',
                'verbose_name_plural': 'Atualizações Diárias de Projeto',
                'ordering': ('-date', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('project', 'date'), name='unique_project_daily_update_per_date')],
            },
        ),
    ]
