# Generated by Django 5.2.5 on 2026-08-15 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clientresponsible'),
        ('updates', '0007_projectdailyupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdailyupdate',
            name='activities_text',
            field=models.TextField(blank=True, help_text='Uma atividade por linha. Preenchido automaticamente ao salvar pela primeira vez.', verbose_name='atividades executadas'),
        ),
        migrations.AddField(
            model_name='projectdailyupdate',
            name='certification_done',
            field=models.BooleanField(default=False, verbose_name='certificação finalizada'),
        ),
        migrations.AddField(
            model_name='projectdailyupdate',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='project_daily_updates', to='core.collaborator', verbose_name='colaboradores'),
        ),
        migrations.AddField(
            model_name='projectdailyupdate',
            name='completion_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='percentual de conclusão'),
        ),
        migrations.AddField(
            model_name='projectdailyupdate',
            name='project_finished',
            field=models.BooleanField(default=False, verbose_name='projeto finalizado'),
        ),
        migrations.AlterField(
            model_name='projectdailyupdate',
            name='summary',
            field=models.TextField(blank=True, help_text='Observações adicionais (opcional).', verbose_name='observações'),
        ),
    ]
