# Generated by Django 5.2.5 on 2026-08-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_projectdailyupdate_activities_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdailyupdate',
            options={'ordering': ('-date', '-created_at'), 'verbose_name': 'Atualização de Projeto', 'verbose_name_plural': 'Atualizações de Projeto'},
        ),
    ]
