# Generated by Django 5.2.5 on 2026-08-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
