# Generated by Django 5.2.5 on 2026-08-16 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_clientresponsible_categories_and_more'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Vincule um Cliente para transformar este usuário num usuário-cliente: ele só verá/editará/excluirá os Projetos deste Cliente (e dos Sites abaixo, se algum for marcado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='core.client', verbose_name='cliente vinculado'),
        ),
        migrations.AddField(
            model_name='user',
            name='client_categories',
            field=models.ManyToManyField(blank=True, help_text='Restringe quais Categorias (cadastro) o usuário-cliente vê/edita/exclui. Vazio = sem restrição.', related_name='portal_users', to='core.category', verbose_name='categorias permitidas'),
        ),
        migrations.AddField(
            model_name='user',
            name='client_sites',
            field=models.ManyToManyField(blank=True, help_text='Restringe o usuário-cliente a estes Sites do Cliente vinculado. Vazio = todos os Sites do Cliente.', related_name='portal_users', to='core.site', verbose_name='sites permitidos'),
        ),
    ]
