# Generated by Django 5.2.5 on 2026-08-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_client_user_client_categories_user_client_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente para usuários recém-criados — força a troca de senha no próximo login, antes de liberar o acesso ao resto do sistema.', verbose_name='precisa trocar a senha'),
        ),
    ]
