# Generated by Django 5.2.5 on 2026-08-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('person_type', models.CharField(choices=[('company', 'Pessoa juridica'), ('person', 'Pessoa fisica')], default='company', max_length=10, verbose_name='tipo de pessoa')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razao social/nome')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('tax_id', models.CharField(max_length=18, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereco')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('registration', models.CharField(max_length=30, verbose_name='matricula')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_types', to='core.category', verbose_name='categoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'tipo de projeto',
                'verbose_name_plural': 'tipos de projeto',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('collaborator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_profile', to='core.collaborator', verbose_name='colaborador vinculado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'responsavel',
                'verbose_name_plural': 'responsaveis',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('code', models.CharField(max_length=30, verbose_name='codigo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereco')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='core.site', verbose_name='sites'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('code', models.CharField(max_length=30, verbose_name='codigo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='horas estimadas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa')),
                ('project_types', models.ManyToManyField(blank=True, related_name='tasks', to='core.projecttype', verbose_name='tipos de projeto')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_category_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'tax_id'), name='unique_client_tax_id_per_company'),
        ),
        migrations.AddConstraint(
            model_name='projecttype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_project_type_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_site_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('company', 'registration'), name='unique_collaborator_registration_per_company'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_task_code_per_company'),
        ),
    ]
