# Generated by Django 5.2.5 on 2026-08-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_client_collaborator_projecttype_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_tax_id_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='collaborator',
            name='unique_collaborator_registration_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='projecttype',
            name='unique_project_type_name_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_site_code_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_code_per_company',
        ),
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='razao social/nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='person_type',
            field=models.CharField(blank=True, choices=[('company', 'Pessoa juridica'), ('person', 'Pessoa fisica')], default='company', max_length=10, verbose_name='tipo de pessoa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='matricula'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='razao social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_types', to='core.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='site',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='horas estimadas'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('company', 'name'), name='unique_category_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('company', 'tax_id'), name='unique_client_tax_id_per_company'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('registration', ''), _negated=True), fields=('company', 'registration'), name='unique_collaborator_registration_per_company'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tax_id',), name='unique_nonempty_company_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='projecttype',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('company', 'name'), name='unique_project_type_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_site_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_task_code_per_company'),
        ),
    ]
