# Generated by Django 5.2.5 on 2026-08-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_title_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='site',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.company', verbose_name='empresa'),
        ),
    ]
