# Generated by Django 5.2.5 on 2026-08-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_company_alter_client_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name__iexact', 'Supervisor'), ('job_title__name__iexact', 'Coordenador'), ('job_title__name__iexact', 'Gerente'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='core.collaborator', verbose_name='gestor'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='yellow_badge',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yellow Badge'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('yellow_badge', ''), _negated=True), fields=('company', 'yellow_badge'), name='unique_collaborator_yellow_badge_per_company'),
        ),
    ]
