# Generated by Django 5.2.5 on 2026-08-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_collaborator_manager_collaborator_yellow_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('job_title__name__icontains', 'Supervisor'), ('job_title__name__icontains', 'Coordenador'), ('job_title__name__icontains', 'Gerente'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='core.collaborator', verbose_name='gestor'),
        ),
    ]
