# Generated by Django 5.2.5 on 2026-08-14 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_collaborator_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='collaborator',
        ),
        migrations.AddField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario vinculado'),
        ),
    ]
