# Generated by Django 5.2.5 on 2026-08-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_responsible_collaborator_responsible_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_company',
        ),
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('name',), name='unique_nonempty_category_name'),
        ),
    ]
