# Generated by Django 5.2.5 on 2026-08-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_category_unique_category_name_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projecttype',
            name='unique_project_type_name_per_company',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='company',
        ),
        migrations.AddConstraint(
            model_name='projecttype',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('name',), name='unique_nonempty_project_type_name'),
        ),
    ]
