# Generated by Django 5.2.5 on 2026-08-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_projecttype_unique_project_type_name_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='category',
        ),
    ]
