# Generated by Django 5.2.5 on 2026-08-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_projecttype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ano')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='ultimo numero')),
            ],
            options={
                'verbose_name': 'sequencia de tarefas',
                'verbose_name_plural': 'sequencias de tarefas',
            },
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_code_per_company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='codigo'),
        ),
    ]
