# Generated by Django 5.2.5 on 2026-08-15 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tasksequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsible',
            options={'ordering': ('name',), 'verbose_name': 'responsável', 'verbose_name_plural': 'responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='tasksequence',
            options={'verbose_name': 'sequência de tarefas', 'verbose_name_plural': 'sequências de tarefas'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='razão social/nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='client',
            name='person_type',
            field=models.CharField(blank=True, choices=[('company', 'Pessoa jurídica'), ('person', 'Pessoa física')], default='company', max_length=10, verbose_name='tipo de pessoa'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='matrícula'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='razão social'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário vinculado'),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='tasksequence',
            name='last_number',
            field=models.PositiveIntegerField(default=0, verbose_name='último número'),
        ),
    ]
