# Generated by Django 5.2.5 on 2026-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_responsible_options_alter_tasksequence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Projeto', 'verbose_name_plural': 'Tipos de Projeto'},
        ),
        migrations.AlterField(
            model_name='task',
            name='project_types',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.projecttype', verbose_name='Tipos de Projeto'),
        ),
    ]
