# Generated by Django 5.2.5 on 2026-08-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_projecttype_options_alter_task_project_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='core.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Responsável do Cliente',
                'verbose_name_plural': 'Responsáveis do Cliente',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('client', 'name'), name='unique_responsible_name_per_client')],
            },
        ),
    ]
