# Generated by Django 5.2.5 on 2026-08-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_collaborator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='geocoded_address',
            field=models.CharField(blank=True, editable=False, help_text='Guarda o endereço que gerou a última latitude/longitude, para saber quando regeocodificar.', max_length=400, verbose_name='endereço geocodificado'),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
