# Generated by Django 5.2.5 on 2026-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_site_geocoded_address_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='manual_coordinates',
            field=models.BooleanField(default=False, help_text='Marque para informar latitude/longitude manualmente. Enquanto marcado, a geocodificação automática não sobrescreve os valores digitados.', verbose_name='coordenadas manuais'),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Preenchida automaticamente a partir do endereço, a menos que 'coordenadas manuais' esteja marcado.", max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Preenchida automaticamente a partir do endereço, a menos que 'coordenadas manuais' esteja marcado.", max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
