# Generated by Django 5.2.5 on 2026-08-16 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0019_site_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, help_text='Restringe quais Categorias (cadastro) são visíveis/editáveis/excluíveis. Vazio = sem restrição.', related_name='access_scopes', to='core.category', verbose_name='categorias permitidas')),
                ('clients', models.ManyToManyField(blank=True, help_text='Restringe os Projetos visíveis/editáveis/excluíveis a estes Clientes. Vazio = sem restrição por Cliente.', related_name='access_scopes', to='core.client', verbose_name='clientes permitidos')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_scope', to='auth.group', verbose_name='grupo')),
                ('sites', models.ManyToManyField(blank=True, help_text='Restringe os Projetos visíveis/editáveis/excluíveis a estes Sites. Vazio = sem restrição por Site.', related_name='access_scopes', to='core.site', verbose_name='sites permitidos')),
            ],
            options={
                'verbose_name': 'Escopo de Acesso do Grupo',
                'verbose_name_plural': 'Escopos de Acesso dos Grupos',
            },
        ),
    ]
