# Generated by Django 5.2.5 on 2026-08-16 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_groupaccessscope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientresponsible',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Restringe quais Categorias (cadastro) o usuário-cliente vê/edita/exclui. Vazio = sem restrição.', related_name='client_responsibles', to='core.category', verbose_name='categorias permitidas'),
        ),
        migrations.AddField(
            model_name='clientresponsible',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Restringe o usuário-cliente a estes Sites do Cliente. Vazio = todos os Sites do Cliente.', related_name='client_responsibles', to='core.site', verbose_name='sites permitidos'),
        ),
        migrations.AddField(
            model_name='clientresponsible',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Vincule um usuário para transformar este contato num usuário-cliente com login: ele só verá/editará/excluirá os Projetos deste Cliente (e dos Sites abaixo, se algum for marcado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_responsible_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário vinculado'),
        ),
        migrations.DeleteModel(
            name='GroupAccessScope',
        ),
    ]
