# Generated by Django 5.2.5 on 2026-08-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clientresponsible_categories_clientresponsible_sites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientresponsible',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='clientresponsible',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='clientresponsible',
            name='user',
        ),
    ]
