# Generated by Django 5.2.5 on 2026-08-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_clientresponsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'ordering': ('person__name',), 'verbose_name': 'técnico', 'verbose_name_plural': 'técnicos'},
        ),
    ]
