# Generated by Django 5.2.5 on 2026-08-16 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_collaborator_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='link')),
                ('project_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id do projeto')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='código do projeto')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-created_at',),
            },
        ),
    ]
