# Generated by Django 5.2.5 on 2026-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('default_unit', models.CharField(blank=True, help_text='Sugestão de unidade pra quantidade (ex: m, un, porta, ponta) — editável por tarefa.', max_length=20, verbose_name='unidade padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividade',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProjectItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Item',
                'verbose_name_plural': 'Tipos de Item',
                'ordering': ('order', 'name'),
            },
        ),
    ]
