# Generated by Django 5.2.5 on 2026-10-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('country', models.CharField(choices=[('BR', 'Brasil'), ('US', 'EUA'), ('CL', 'Chile'), ('MX', 'México')], default='BR', max_length=2, verbose_name='país')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'região',
                'verbose_name_plural': 'regiões',
                'ordering': ('country', 'name'),
            },
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='core.region', verbose_name='região'),
        ),
    ]
