# Generated by Django 5.2.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_seed_activity_and_item_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('technology', models.CharField(max_length=100, unique=True, verbose_name='tecnologia')),
                ('name', models.CharField(blank=True, help_text="Rótulo amigável opcional, ex: 'Robust 2F padrão'.", max_length=150, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Regra de Geração',
                'verbose_name_plural': 'Regras de Geração',
                'ordering': ('technology',),
            },
        ),
        migrations.CreateModel(
            name='GenerationRuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_steps', to='core.activitytype', verbose_name='tipo de atividade')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.generationrule', verbose_name='regra')),
            ],
            options={
                'verbose_name': 'Etapa da Regra',
                'verbose_name_plural': 'Etapas da Regra',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='generationrulestep',
            constraint=models.UniqueConstraint(fields=('rule', 'activity_type'), name='unique_step_per_rule'),
        ),
    ]
